Fixed l3mh automation case for rhosp
partial-jira-bug: CEM-24539
Change-Id: I31bc10aa2e9847823f8d6a42091c6cc4b80ac34e

diff --git a/containers/vrouter/base/network-functions-vrouter-dpdk b/containers/vrouter/base/network-functions-vrouter-dpdk
--- a/containers/vrouter/base/network-functions-vrouter-dpdk
+++ b/containers/vrouter/base/network-functions-vrouter-dpdk
@@ -132,6 +132,36 @@ function ifcfg_read_phys_int_mac_pci_dpdk() {
     echo $phys_int $phys_int_mac $pci
 }
 
+function l3mh_dpdk_create_interfaces_and_routes() {
+    local phys_int_arr="$@"
+    local phys_int
+    local phys_int_mac
+    local phys_int_ip
+    local i=0
+    local tap
+    local ip_loopback
+    echo "INFO: Creating tuntap interfaces and routes (L3MH-DPDK case)"
+    for phys_int in ${phys_int_arr[@]}; do
+        tap="tap${i}"
+        phys_int_mac=$(cat $binding_data_dir/${phys_int}_mac)
+        echo "DEBUG: ip link set dev ${tap} address ${phys_int_mac}"
+        ip link set dev ${tap} address ${phys_int_mac}
+        cat $binding_data_dir/${phys_int}_ip_addresses | while IFS= read -r phys_int_ip ; do
+            echo "DEBUG: ip addr add ${phys_int_ip} dev ${tap}"
+            ip addr add ${phys_int_ip} dev ${tap}
+        done
+        echo "DEBUG: ip link set dev ${tap} up"
+        ip link set dev ${tap} up
+        i=$[$i+1]
+    done
+    #Adding static routes
+    ip_loopback=$(eval_l3mh_loopback_ip)
+    echo "DEBUG: ip route add table 100 to default dev vhost0"
+    ip route add table 100 to default dev vhost0
+    echo "DEBUG: ip rule add from ${ip_loopback} table 100"
+    ip rule add from ${ip_loopback} table 100
+}
+
 function start_dpdk_container() {
     [ -z "$CONTRAIL_VROUTER_AGENT_DPDK_DOCKER_IMAGE" ] && \
         { echo 'ERROR: CONTRAIL_VROUTER_AGENT_DPDK_DOCKER_IMAGE is not provided' && return 1; }
@@ -148,6 +178,9 @@ function start_dpdk_container() {
     [ -n "$DPDK_COMMAND_ADDITIONAL_ARGS" ] && env_options+=" -e \"DPDK_COMMAND_ADDITIONAL_ARGS=$DPDK_COMMAND_ADDITIONAL_ARGS\""
     [ -n "$NIC_OFFLOAD_ENABLE" ] && env_options+=" -e \"NIC_OFFLOAD_ENABLE=$NIC_OFFLOAD_ENABLE\""
     [ -n "$LACP_RATE" ] && env_options+=" -e \"LACP_RATE=$LACP_RATE\""
+    [ -n "$L3MH_CIDR" ] && env_options+=" -e \"L3MH_CIDR=$L3MH_CIDR\""
+    [ -n "$LOG_LEVEL" ] && env_options+=" -e \"LOG_LEVEL=$LOG_LEVEL\""
+    [ -n "$VROUTER_GATEWAY" ] && env_options+=" -e \"VROUTER_GATEWAY=$VROUTER_GATEWAY\""
 
     local cmd=$(which podman 2>/dev/null || echo docker)
     local container_name=${CONTRAIL_VROUTER_AGENT_DPDK_CONTAINER_NAME:-'contrail-vrouter-agent-dpdk'}
@@ -282,12 +315,22 @@ function restore_phys_int_dpdk_l3mh() {
 
 function ifup_init_vhost() {
     ip addr show dev vhost0 >/dev/null 2>&1 && return 0
-    local phys_int=${BIND_INT}
     if [[ -n "$L3MH_CIDR" ]]; then
-        [ -z "$phys_int" ] && { echo "ERROR: BIND_INT in not set in ifcfg-vhost0" && return 1; }
         ifup_init_vhost_l3mh
     else
         ifup_init_vhost_classic
+    fi
+}
+
+function ifup_init_vhost_start_dpdk() {
+    prepare_vif_config $TYPE
+    # ifup could be called from host (osp) and container (k8s, rhel, etc),
+    # in context of host - it should just start container and
+    # wait till container creates vhost0
+    if [[ -z "$CONTRAIL_DPDK_CONTAINER_CONTEXT" ]] ; then
+        start_dpdk_container || return 1
+        wait_dpdk_start || return 1
+        wait_vhost0 || return 1
     fi
 }
 
@@ -297,15 +340,7 @@ function ifup_init_vhost_classic() {
     [ -z "$pci" ] && { echo "ERROR: BIND_INT in not set in ifcfg-vhost0" && return 1; }
     [ -z "$phys_int" ] && { echo "ERROR: failed to detect ifname by pci $pci" && return 1; }
     [ -z "$phys_int_mac" ] && { echo "ERROR: failed to detect MAC for $phys_int" && return 1; }
-    prepare_vif_config $TYPE
-    # ifup could be called from host (osp) and container (k8s, hel, etc),
-    # in context of host - it should just start container and
-    # wait till container creates vhost0
-    if [[ -z "$CONTRAIL_DPDK_CONTAINER_CONTEXT" ]] ; then
-        start_dpdk_container || return 1
-        wait_dpdk_start || return 1
-        wait_vhost0 || return 1
-    fi
+    ifup_init_vhost_start_dpdk
 }
 
 function prepare_ifcfg_l3mh() {
@@ -360,19 +395,7 @@ EOF
 }
 
 function ifup_init_vhost_l3mh() {
-    local phys_ints=${BIND_INT}
-    # up iface to read info from it on next steps
-    declare phys_int_mac_list phys_int
-    for phys_int in $(echo $phys_ints | tr ',' ' ') ; do
-        ifup ${phys_int}
-        if [ -z $phys_int_mac_list ]; then
-            phys_int_mac_list+=$(get_iface_mac $phys_int)
-        else
-           phys_int_mac_list+=","
-           phys_int_mac_list+=$(get_iface_mac $phys_int)
-        fi
-    done
-    create_vhost0 $phys_ints $phys_int_mac_list $L3MH_VRRP_MAC
+    ifup_init_vhost_start_dpdk
 }
 
 # ifdown interface
@@ -387,12 +410,11 @@ function ifdown_vhost() {
 function ifdown_vhost_post() {
     [ -n "$CONTRAIL_DPDK_CONTAINER_CONTEXT" ] && {
         echo "ERROR: container context... should not be called from container" && return 1 ; }
-    local pci=${BIND_INT}
-    [ -z "$pci" ] && { echo "ERROR: BIND_INT in not set in ifcfg-vhost0" && return 1; }
     if [[ -n "$L3MH_CIDR" ]]; then
         restore_phys_int_dpdk_l3mh $DRIVER
     else
-        restore_phys_int_dpdk $pci $DRIVER
+        [ -z "$BIND_INT" ] && { echo "ERROR: BIND_INT in not set in ifcfg-vhost0" && return 1; }
+        restore_phys_int_dpdk $BIND_INT $DRIVER
     fi
 }
 
