L3MH-dpdk bugfix
partial-jira-bug: CEM-21574
Signed-off-by: Gleb Galkin <gleb108@gmail.com>
Change-Id: Ifa635bcafbaea5396931d74b22f0b88810296617

diff --git a/containers/vrouter/base/network-functions-vrouter-dpdk b/containers/vrouter/base/network-functions-vrouter-dpdk
--- a/containers/vrouter/base/network-functions-vrouter-dpdk
+++ b/containers/vrouter/base/network-functions-vrouter-dpdk
@@ -18,7 +18,20 @@ function wait_dpdk_start() {
     return 1
 }
 
+#L3MH case
+function get_static_dpdk_routes() {
+    #List of control nodes ip addresses (separated by spaces)
+    local control_node_list=$1
+    local ipaddr route
+    for ipaddr in $control_node_list; do
+        #Getting route and join it in one line
+        route=$(ip route show $ipaddr | sed -E 's/dev [a-z0-9]+ //' | tr '\n' ' ' | sed -E 's/\s+/ /g')
+        echo "$route"
+    done
+}
+
 function create_vhost0_dpdk() {
+    echo "$DEBUG: create_vhost0_dpdk()"
     local phys_int=$1
     local phys_int_mac=$2
     echo "INFO: Creating ${phys_int} interface with mac $phys_int_mac via vif utility..."
@@ -40,6 +53,39 @@ function create_vhost0_dpdk() {
         return 1
     fi
 }
+
+function create_vhost0_l3mh_dpdk() {
+    echo "DEBUG: create_vhost0_l3mh_dpdk()"
+    local binding_data_dir='/var/run/vrouter'
+    local phys_int_list=$(cat ${binding_data_dir}/nic)
+    local phys_int phys_int_mac
+    local i=0
+    for phys_int in $phys_int_list; do
+        phys_int_mac=$(cat ${binding_data_dir}/${phys_int}_mac)
+        echo "INFO: Creating $phys_int interface with mac $phys_int_mac via vif utility. (id=$i)"
+        echo "DEBUG: vif --add 0 --mac ${phys_int_mac} --vrf 0 --vhost-phys --type physical --pmd --id ${i}"
+        if ! vif --add ${i} --mac ${phys_int_mac} --vrf 0 --vhost-phys --type physical --pmd --id ${i} ; then
+            echo "ERROR: Failed to adding ${phys_int} interface via vif"
+            return 1
+        fi
+        i=$[$i+1]
+    done
+    echo "INFO: Adding vhost0 interface with vif utility. (id=$i)"
+    echo "DEBUG: vif --add vhost0 --mac ${L3MH_VRRP_MAC} --vrf 0 --type vhost --xconnect 0 --pmd --id ${i}"
+    if ! vif --add vhost0 --mac ${L3MH_VRRP_MAC} --vrf 0 --type vhost --xconnect 0 --pmd --id ${i} ; then
+        echo "ERROR: Failed to add vhost0 interface"
+        return 1
+    fi
+    if ! ip link set dev vhost0 address ${L3MH_VRRP_MAC} ; then
+        echo "ERROR: Failed to set vhost0 address ${L3MH_VRRP_MAC}"
+        return 1
+    fi
+    if ! ip link set dev vhost0 up ; then
+        echo "ERROR: Failed to up vhost0 interface"
+        return 1
+    fi
+}
+
 
 function get_next_free_bond_name() {
     local i=0
@@ -262,3 +308,5 @@ function ifdown_vhost_post() {
     [ -z "$pci" ] && { echo "ERROR: BIND_INT in not set in ifcfg-vhost0" && return 1; }
     restore_phys_int_dpdk $pci $DRIVER
 }
+
+
